const footer = (() => {
  const footer = document.createElement("footer");
  footer.setAttribute("class", "weekly");
  const currentDiv = document.createElement("div");
  currentDiv.setAttribute("class", "current");
  const currentList = document.createElement("ul");
  const currentHead = document.createElement("li");
  currentHead.innerHTML = "Current Weather";
  const currentIcon = document.createElement("li");
  currentIcon.setAttribute("class", "icon2");
  const canvasIcon = document.createElement("canvas");
  canvasIcon.setAttribute("id", "icon");
  canvasIcon.setAttribute("width", "100");
  canvasIcon.setAttribute("height", "100");
  const currentTempDesc = document.createElement("li");
  currentTempDesc.setAttribute("class", "currentTempDesc");
  const TodayDiv = document.createElement("div");
  TodayDiv.setAttribute("class", "today");
  const TodayList = document.createElement("ul");
  const TodayDesc = document.createElement("li");
  TodayDesc.innerHTML = "Today's High";
  const TodayIcon = document.createElement("li");
  TodayIcon.setAttribute("class", "icon2");
  const canvasIconToday = document.createElement("canvas");
  canvasIconToday.setAttribute("id", "icon3");
  canvasIconToday.setAttribute("width", "100");
  canvasIconToday.setAttribute("height", "100");
  const TodayTemp = document.createElement("li");
  TodayTemp.setAttribute("class", "TodayTemp");
  const TonightDiv = document.createElement("div");
  TonightDiv.setAttribute("class", "tonight");
  const TonightList = document.createElement("ul");
  const TonightDesc = document.createElement("li");
  TonightDesc.innerHTML = "Tonight's Low";
  const TonightIcon = document.createElement("li");
  TonightIcon.setAttribute("class", "icon2");
  const canvasIconTonight = document.createElement("canvas");
  canvasIconTonight.setAttribute("id", "icon4");
  canvasIconTonight.setAttribute("width", "130");
  canvasIconTonight.setAttribute("height", "130");
  const TonightTemp = document.createElement("li");
  TonightTemp.setAttribute("class", "TonightTemp");
  const TomorrowDiv = document.createElement("div");
  TomorrowDiv.setAttribute("class", "tomorrow");
  const TomorrowList = document.createElement("ul");
  const TomorrowDesc = document.createElement("li");
  TomorrowDesc.innerHTML = "Tomorrow";
  const TomorrowIcon = document.createElement("li");
  TomorrowIcon.setAttribute("class", "icon2");
  const canvasIconTomorrow = document.createElement("canvas");
  canvasIconTomorrow.setAttribute("id", "icon5");
  canvasIconTomorrow.setAttribute("width", "100");
  canvasIconTomorrow.setAttribute("height", "100");
  const TomorrowTemp = document.createElement("li");
  TomorrowTemp.setAttribute("class", "TomorrowTemp");

  TomorrowIcon.appendChild(canvasIconTomorrow);
  TomorrowIcon.appendChild(TomorrowTemp);
  TomorrowDesc.appendChild(TomorrowIcon);
  TomorrowList.appendChild(TomorrowDesc);
  TomorrowDiv.appendChild(TomorrowList);
  TonightIcon.appendChild(canvasIconTonight);
  TonightIcon.appendChild(TonightTemp);
  TonightDesc.appendChild(TonightIcon);
  TonightList.appendChild(TonightDesc);
  TonightDiv.appendChild(TonightList);
  TodayIcon.appendChild(canvasIconToday);
  TodayIcon.appendChild(TodayTemp);
  TodayDesc.appendChild(TodayIcon);
  TodayList.appendChild(TodayDesc);
  TodayDiv.appendChild(TodayList);
  currentIcon.appendChild(canvasIcon);
  currentIcon.appendChild(currentTempDesc);
  currentHead.appendChild(currentIcon);
  currentList.appendChild(currentHead);
  currentDiv.appendChild(currentList);

  footer.appendChild(currentDiv);
  footer.appendChild(TodayDiv);
  footer.appendChild(TonightDiv);
  footer.appendChild(TomorrowDiv);

  return footer;
})();

export default footer;
